### ISSUE TITLE
App crashs on some Android 9.0 devices

### ISSUE THREAD

**Issue by nguyenxuankiet262** [miguelpruivo/plugins_flutter_file_picker#105]
I cannot upload image from gallery. This is my logcat
FileSystemException: Cannot open file, path = '/storage/emulated/0/zalo/picture/IMG_UPLOAD_20190711_000720.jpg' (OS Error: Permission denied, errno = 13)

**Comment by miguelpruivo** [comment]
Hi, Android 9.0 isn’t yet supported. 

Thank you.

**Comment by nguyenxuankiet262** [comment]
Hope you soon upgrade this package!

**Comment by miguelpruivo** [comment]
Hi again @nguyenxuankiet262 somehow I was thinking in API 29 (Android Q) and not 9.0 (API 28) which is supported for a while now. 

So, that means you shouldn’t experience any issue, but by looking at your logs looks like you didn’t provide read permissions for accessing that file. Do you have the `READ` permission it on your manifest file? 

If so, just make sure you’re on the latest version of the plugin and clean and build the project again. 

Thank you!

**Comment by nguyenxuankiet262** [comment]
I tested on many devices. Only android 9.0 devices get this issuse

**Comment by nguyenxuankiet262** [comment]
Oh no sorry. It's not working on any devices, it just shows but cannot be uploaded. My manifest have READ Permission.

**Comment by nguyenxuankiet262** [comment]
My fault!!! I really apologize to you because my function resize image when i upload image
