### ISSUE TITLE
Depending on File Picker causes app to not build

### ISSUE THREAD

**Issue by Ca1iburn** [miguelpruivo/plugins_flutter_file_picker#113]
If I add File Picker to my dependencies the app is no longer able to build to an android emulator.

My debug console returns:
` D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

//list of numbered debug.jars

Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver `

and

` BUILD FAILED in 12s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1 `

I'm new to flutter and app development so I've read the pages it suggests to resolve the issue but don't know how to proceed.

edit: Looking into it more I think it's probably a shared dependency conflict with a different package so I'll try looking into that and report back.

edit2: It seems like the conflict is with Simple Permissions. I'm running file_picker 1.3.8 and simple_permissions 0.1.9

**Comment by Ca1iburn** [comment]
I didn't find the exact issue but I imagine it's on Simple Permissions due to it having not been updated in quite a while. I found an alternative to SP (that actually looks like it'll be better) with Permission Handler.

**Comment by miguelpruivo** [comment]
So, basically @Ca1iburn, this has nothing to do directly with this package right? If so, feel free to close the issue or let it open otherwise.

Thank you.

**Comment by miguelpruivo** [comment]
Looks like you managed to solve it. Closing due to no further response.
