### ISSUE TITLE
limit the maximum selected file

### ISSUE THREAD

**Issue by dsourav** [miguelpruivo/plugins_flutter_file_picker#118]
i want to add limit so that user can select according to the limit

**Comment by miguelpruivo** [comment]
Hi @dsourav, currently this is not possible according to the [docs](https://developer.android.com/reference/android/content/Intent.html#EXTRA_ALLOW_MULTIPLE). 

> Extra used to indicate that an intent can allow the user to select and return multiple items. This is a boolean extra; the default is false. If true, an implementation is allowed to present the user with a UI where they can pick multiple items that are all returned to the caller. When this happens, they should be returned as the getClipData() part of the result Intent.

Basically, there's only a `boolean` option that either allows the user to pick multiple files or not. You have to handle that limit on your end with something like showing the user an info regarding the limit and discarding the others.

Thank you.

**Comment by dsourav** [comment]
why are you closing the issue.Give some proper example.

**Comment by miguelpruivo** [comment]
@dsourav there's no proper example to be given, I've explained in my previous answer that currently that is not possible due to Android API limitation.

**Comment by miguelpruivo** [comment]
@dsourav there's no proper example to be given, I've explained in my previous answer that currently that is not possible due to an Android API limitation.

**Comment by dsourav** [comment]
then i think the issue must not be closed.

**Comment by miguelpruivo** [comment]
@dsourav this one should because it's something that native Android API is restricting. Leaving this open would feel that is something directly related to **_this_** plugin and that should be fixed by it, when it's not.

**Comment by dsourav** [comment]
ok i got this. thanks for your contribution..
