### ISSUE TITLE
File picker default page

### ISSUE THREAD

**Issue by premtemp1** [miguelpruivo/plugins_flutter_file_picker#121]
Hello,
  The default landing page for the picker on iOS phones is iCloud and the local browser for android.. This seems to be the last page that visited

is there an option to have the landing page be be the main page for the browser that shows the user all the file picker option(dropbox , gdrive etc)

Thanks

**Comment by miguelpruivo** [comment]
Hi @premtemp1, I’m afraid that this is not possible as it is automatically handled by the OS itself, after the intent is sent and based on the file extension filters.
