### ISSUE TITLE
Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0-beta01'

### ISSUE THREAD

**Issue by Zeeshan0201** [miguelpruivo/plugins_flutter_file_picker#122]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:lintVitalRelease'.                      
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve androidx.appcompat:appcompat:1.0.0-beta01.       
     Required by:                                                       
         project :app                                                   
      > Cannot find a version of 'androidx.appcompat:appcompat' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0-beta01'
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0'
                                                                        
   > Could not resolve androidx.vectordrawable:vectordrawable:1.0.0-beta01.
     Required by:                                                       
         project :app                                                   
      > Cannot find a version of 'androidx.vectordrawable:vectordrawable' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0'
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0'
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0'
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
                                                                        
   > Could not resolve androidx.vectordrawable:vectordrawable-animated:1.0.0-beta01.
     Required by:                                                       
         project :app                                                   
      > Cannot find a version of 'androidx.vectordrawable:vectordrawable-animated' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0'
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0'
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable-animated' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable-animated' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
                                                                        
   > Could not resolve androidx.appcompat:appcompat:1.0.0-beta01.       
     Required by:                                                       
         project :app > project :file_picker                            
      > Cannot find a version of 'androidx.appcompat:appcompat' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0-beta01'
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0'
                                                                        
   > Could not resolve androidx.appcompat:appcompat:1.0.0.              
     Required by:                                                       
         project :app > androidx.test.espresso:espresso-contrib:3.2.0-alpha02 > com.google.android.material:material:1.0.0
      > Cannot find a version of 'androidx.appcompat:appcompat' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0-beta01'
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.appcompat:appcompat' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0'
                                                                        
   > Could not resolve androidx.vectordrawable:vectordrawable:1.0.0.    
     Required by:                                                       
         project :app > androidx.appcompat:appcompat:1.0.0              
         project :app > androidx.vectordrawable:vectordrawable-animated:1.0.0
      > Cannot find a version of 'androidx.vectordrawable:vectordrawable' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0'
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0'
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0' --> 'androidx.vectordrawable:vectordrawable:1.0.0'
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
                                                                        
   > Could not resolve androidx.vectordrawable:vectordrawable-animated:1.0.0.
     Required by:                                                       
         project :app > androidx.appcompat:appcompat:1.0.0              
      > Cannot find a version of 'androidx.vectordrawable:vectordrawable-animated' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'com.mr.flutter.plugin.filepicker:file_picker:1.0-SNAPSHOT' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0'
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02' --> 'com.google.android.material:material:1.0.0' --> 'androidx.appcompat:appcompat:1.0.0' --> 'androidx.vectordrawable:vectordrawable-animated:1.0.0'
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable-animated' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
           Constraint path 'android:app:unspecified' --> 'androidx.vectordrawable:vectordrawable-animated' strictly '1.0.0-beta01' because of the following reason: debugRuntimeClasspath uses version 1.0.0-beta01
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       1.8s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1

**Comment by Zeeshan0201** [comment]
@miguelpruivo can you please check this? getting build error due to some of incompatibilities with file_picker..

**Comment by miguelpruivo** [comment]
Looks like you don’t have Android X compatibility in your app. See [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility)

**Comment by Zeeshan0201** [comment]
@miguelpruivo my app is compatible with Android X, I already checked that docs..

**Comment by miguelpruivo** [comment]
What’s the minimum and target version of your Android app?

**Comment by Zeeshan0201** [comment]
@miguelpruivo   minSdkVersion 16, targetSdkVersion 28

**Comment by Zeeshan0201** [comment]
@miguelpruivo i am able to run and build debug app, only logs error came when i was trying to release build.

**Comment by miguelpruivo** [comment]
@Zeeshan0201 that's odd. What's the copile version in the `build.gradle` as well?

**Comment by Zeeshan0201** [comment]
@miguelpruivo 
![Screenshot from 2019-08-05 15-51-46](https://user-images.githubusercontent.com/45591301/62457681-f2ec5f80-b798-11e9-98a7-224408d23f94.png)

**Comment by Zeeshan0201** [comment]
and @miguelpruivo thanks for your quick response..

**Comment by miguelpruivo** [comment]
@Zeeshan0201 not that `build.gradle`, the one in your app folder. 👍

**Comment by Zeeshan0201** [comment]
@miguelpruivo yes i edited it :smile:  **compileSdkVersion 28**

**Comment by miguelpruivo** [comment]
Mind to `flutter clean` and `flutter build apk --release` again? That's somehow weird.

**Comment by Zeeshan0201** [comment]
@miguelpruivo it's taking time for build,will inform once it's complete.

**Comment by Zeeshan0201** [comment]
![Screenshot from 2019-08-05 16-00-49](https://user-images.githubusercontent.com/45591301/62458316-34c9d580-b79a-11e9-88d7-b82e714de3b9.png)
still coming :con]

**Comment by miguelpruivo** [comment]
Can you please show me your `android/app/build.gradle`? You are showing the `android/build.gradle`.

**Comment by Zeeshan0201** [comment]
> def localProperties = new Properties()
> def localPropertiesFile = rootProject.file('local.properties')
> if (localPropertiesFile.exists()) {
>     localPropertiesFile.withReader('UTF-8') { reader ->
>         localProperties.load(reader)
>     }
> }
> 
> def flutterRoot = localProperties.getProperty('flutter.sdk')
> if (flutterRoot == null) {
>     throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
> }
> 
> def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
> if (flutterVersionCode == null) {
>     flutterVersionCode = '1'
> }
> 
> def flutterVersionName = localProperties.getProperty('flutter.versionName')
> if (flutterVersionName == null) {
>     flutterVersionName = '1.0'
> }
> 
> apply plugin: 'com.android.application'
> apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
> 
> android {
>     compileSdkVersion 28
> 
>     lintOptions {
>         disable 'InvalidPackage'
>     }
> 
>     defaultConfig {
>         // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
>         applicationId "com.example.thundermobile"
>         minSdkVersion 16
>         targetSdkVersion 28
>         versionCode flutterVersionCode.toInteger()
>         versionName flutterVersionName
>         testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
>         multiDexEnabled true
>     }
> 
>     buildTypes {
>         release {
>             // TODO: Add your own signing config for the release build.
>             // Signing with the debug keys for now, so `flutter run --release` works.
>             signingConfig signingConfigs.debug
>             minifyEnabled true
>             useProguard true
>             // shrinkResources true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
>         }
>     }
> }
> 
> flutter {
>     source '../..'
> }
> 
> dependencies {
>     testImplementation 'junit:junit:4.12'
>     androidTestImplementation 'androidx.test:runner:1.1.1'
>     androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0-alpha02'
>     androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02'
>     implementation 'com.google.firebase:firebase-firestore:18.0.0'
>     implementation 'com.google.firebase:firebase-core:16.0.6'
>     implementation 'com.google.firebase:firebase-auth:16.1.0'
>     implementation 'com.google.android.gms:play-services-auth:16.0.1'
>     implementation 'com.google.firebase:firebase-database:16.0.6'
>     
> }
> 
> apply plugin: 'com.google.gms.google-services'
>

**Comment by Zeeshan0201** [comment]
@miguelpruivo please check :arrow_up:

**Comment by miguelpruivo** [comment]
Replace those two
```
androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0-alpha02'
androidTestImplementation 'androidx.test.espresso:espresso-contrib:3.2.0-alpha02'
```
 with one line only of
```
androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
```

Also, I don't get why you have a `flutter` dependency there.

Make sure you `flutter clean` before building again, after these changes.

**Comment by Zeeshan0201** [comment]
@miguelpruivo okay,checking

**Comment by Zeeshan0201** [comment]
This is taking an unexpectedly long time. @miguelpruivo

**Comment by Zeeshan0201** [comment]
and yeah it's done without error :small_airplane:

**Comment by Zeeshan0201** [comment]
but slightly it's size increases, by the way thanks a lot ! :pray:  @miguelpruivo

**Comment by miguelpruivo** [comment]
@Zeeshan0201 glad that it worked for you. As for the size itself, you must look to your dependencies and see which ones you really need to. You may not need that dependency at all, if you're not going to do unit tests for that Android project.

**Comment by miguelpruivo** [comment]
@Zeeshan0201 glad that it worked for you. As for the size itself, you must look to your dependencies and see which ones you really need to. You may not need that dependency at all, if you're not going to run unit tests for that Android project.
