### ISSUE TITLE
Not opening Picker dailog

### ISSUE THREAD

**Issue by engdinesh** [miguelpruivo/plugins_flutter_file_picker#123]
I am getting this error :

I/FilePicker( 7260): Checking permission: android.permission.READ_EXTERNAL_STORAGE
I/FilePicker( 7260): Requesting permission: android.permission.READ_EXTERNAL_STORAGE

**Comment by miguelpruivo** [comment]
Hi @engdinesh you must give read external permissions (when the dialog pops) to access those file locations. If you've already dismissed it, you may have to uninstall/reinstall the app again for it to show up again.

Also, you can easily go to the app permission's settings and give the permission manually.

**Comment by miguelpruivo** [comment]
Is this solved @engdinesh ?

**Comment by miguelpruivo** [comment]
Closing this to no further details. Feel free to reopen if the problem still persists.
