### ISSUE TITLE
ld: library not found for -lfile_picker

### ISSUE THREAD

**Issue by YourksChan** [miguelpruivo/plugins_flutter_file_picker#124]

**Comment by miguelpruivo** [comment]
I need more details on this... thank you.

**Comment by YourksChan** [comment]
`
Showing Recent Messages
Ld /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner normal arm64 (in target: Runner)
    cd /Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos -L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker -L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker -L/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Flutter -F/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos -F/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Pods/../.symlinks/flutter/ios -F/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Pods/../.symlinks/flutter/ios -F/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Flutter -filelist /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_lto.o -Xlinker -final_output -Xlinker /Applications/Runner.app/Runner -fobjc-arc -fobjc-link-runtime -ObjC -lfile_picker -framework Flutter -ObjC -lfile_picker -framework Flutter -framework Flutter -framework App -lPods-Runner -Xlinker -dependency_info -Xlinker /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner_dependency_info.dat -o /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/Runner

ld: warning: directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'
ld: warning: directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'
ld: library not found for -lfile_picker
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`






`ld: warning: directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'
ld: warning: directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'
ld: library not found for -lfile_picker
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`







`
Showing Recent Messages
:-1: Directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'

`


`
Showing Recent Messages
:-1: Directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'

`


`
Showing Recent Messages
:-1: Library not found for -lfile_picker

`







`
Showing Recent Messages
Ld /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner normal armv7 (in target: Runner)
    cd /Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos -L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker -L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker -L/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Flutter -F/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos -F/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Pods/../.symlinks/flutter/ios -F/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Pods/../.symlinks/flutter/ios -F/Users/yourks/AndroidStudioProjects/flutter_build_ios_err/ios/Flutter -filelist /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner_lto.o -Xlinker -final_output -Xlinker /Applications/Runner.app/Runner -fobjc-arc -fobjc-link-runtime -ObjC -lfile_picker -framework Flutter -ObjC -lfile_picker -framework Flutter -framework Flutter -framework App -lPods-Runner -Xlinker -dependency_info -Xlinker /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner_dependency_info.dat -o /Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/Runner

ld: warning: directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'
ld: warning: directory not found for option '-L/Users/yourks/Library/Developer/Xcode/DerivedData/Runner-biktrvawzdnbbscsigvkpphrbadd/ArchiveIntermediates/Runner/BuildProductsPath/Release-iphoneos/file_picker'
ld: library not found for -lfile_picker
clang: error: linker command failed with exit code 1 (use -v to see invocation)

`


<img width="1137" alt="image" src="https://user-images.githubusercontent.com/50285055/62778495-1db11d80-bae3-11e9-931d-d8fbe80af0f1.png">

**Comment by YourksChan** [comment]
Flutter 1.8.5-pre.96 • channel master • https://github.com/flutter/flutter.git
Framework • revision 2368b9657b (7 hours ago) • 2019-08-09 01:27:36 -0400
Engine • revision dd735c9179
Tools • Dart 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)

**Comment by YourksChan** [comment]
pod --version
1.7.5

**Comment by YourksChan** [comment]
Xcode 10.2.1
Build version 10E1001

**Comment by YourksChan** [comment]
I just create a flutter project, import the file_picker plugin, and package the ipa

**Comment by miguelpruivo** [comment]
How are you adding the plugin to your project? Can you show me?

**Comment by YourksChan** [comment]
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/50285055/62778961-6e754600-bae4-11e9-98fd-0bae1739a6cd.png">

**Comment by miguelpruivo** [comment]
Ok, that looks correct. Mind to `flutter clean` and `flutter build ios` in the console?

**Comment by YourksChan** [comment]
flutter build ios Is the right.

But I want to generate a.ipa file because I don't know how to distribute the.app

**Comment by miguelpruivo** [comment]
What if you do `flutter build ios --release`? It will create the .ipa file you're looking for.

**Comment by YourksChan** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/50285055/62779414-bfd20500-bae5-11e9-9f3a-c2841becd4bb.png">

It's a.app..

**Comment by miguelpruivo** [comment]
You need to archive after that. You may be doing something wrong while archiving.

**Comment by YourksChan** [comment]
May I have your contact information?
I don't know how to solve this problem at present..

**Comment by miguelpruivo** [comment]
Make sure you are archiving in the generic emulator selected.

**Comment by miguelpruivo** [comment]
I'm closing this since it is out of the plugin's scope. Feel free to keep the discussion on if you still have any _offtopic_ question related to this.
