### ISSUE TITLE
Android - got ClassCastException from checkPermission() and requestPermission()

### ISSUE THREAD

**Issue by thomasycf** [miguelpruivo/plugins_flutter_file_picker#125]
I got below error when I tried to call FilePicker.getFilePath().
java.lang.ClassCastException: com.example.pick_video.MainActivity cannot be cast to androidx.appcompat.app.AppCompatActivity

When I stack trace the AppCompatActivity object in these 2 function- checkPermission() and requestPermission(), both return NullPointerException.

So I changed the activity object type from AppCompatActivity to Activity and it works.  Is this the right solution to fix the problem?

private static boolean checkPermission() {
    Activity activity =  instance.activity();
    Log.i(TAG, "Checking permission: " + permission);
    return PackageManager.PERMISSION_GRANTED == ContextCompat.checkSelfPermission(activity, permission);
  }

  private static void requestPermission() {
    Activity activity = instance.activity();
    Log.i(TAG, "Requesting permission: " + permission);
    String[] perm = { permission };
    ActivityCompat.requestPermissions(activity, perm, PERM_CODE);
  }

**Comment by miguelpruivo** [comment]
Yes, you need to have full Android X support as mentioned [here](https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility).

**Comment by thomasycf** [comment]
Thanks very much for prompt reply
