### ISSUE TITLE
How can i get multiple file object ?

### ISSUE THREAD

**Issue by Zeeshan0201** [miguelpruivo/plugins_flutter_file_picker#128]
> How can I get multiple file object as we did for a single file by  **getFile** Method?

**Comment by miguelpruivo** [comment]
You don’t, but the `getFile` is just a helper method that wraps the picked path into a `File(path)`. Nothing else. So you can iterate for all the path values that you get from the `getMultiPath` and populate a `List<File>` yourself.

**Comment by Zeeshan0201** [comment]
@miguelpruivo I need to copy multiple files into getApplicationDocumentsDirectory as I did for the single file using `getFile` Method like this  ` await file.copy('$savedDir/$fileName');` but now not able to copy multiple files just because I am getting paths instead of files...

**Comment by miguelpruivo** [comment]
You need to create a `File()` with the path for each path, as such: `File(path)`

**Comment by Zeeshan0201** [comment]
@miguelpruivo okay trying with it!

**Comment by miguelpruivo** [comment]
Hi, just to let you know that in the next release there will be a `getMultiFile` method that will do that work for you, based on your suggestion.

Thank you.

**Comment by Zeeshan0201** [comment]
@miguelpruivo haha, thanks a lot ! 😊

**Comment by miguelpruivo** [comment]
@Zeeshan0201 done, can you check the `beta` branch on your project and see if its working for your needs? Replace in the pubspec.yaml like so:
```
file_picker:
    git:
      url: https://github.com/miguelpruivo/plugins_flutter_file_picker.git
      ref: beta
```

**Comment by Zeeshan0201** [comment]
@miguelpruivo great ! Will try and respond 👍

**Comment by Zeeshan0201** [comment]
@miguelpruivo it's working awesome :+1: ready for release new version :rocket:

**Comment by Zeeshan0201** [comment]
@miguelpruivo can you please check this,can you make packages regarding this?
`https://stackoverflow.com/questions/58037603/how-can-i-force-stop-any-application-using-flutter`

**Comment by miguelpruivo** [comment]
@Zeeshan0201 I’m afraid that that is controlled by the system itself and you _shouldn’t_ be able to do this. The app should be properly closed with a sigterm command, in the best scenario.

**Comment by Zeeshan0201** [comment]
@miguelpruivo I just want to turn off the internet of the particular application without turning of device internet connection, so thought by force stop that application we can do it...and I want to make an application on it...

**Comment by Zeeshan0201** [comment]
@miguelpruivo can you please reply if possible?

**Comment by miguelpruivo** [comment]
@Zeeshan0201 which application are you relating to? It's an app that you are the owner?

**Comment by Zeeshan0201** [comment]
@miguelpruivo  _please check this, I haven't currently this type of app, I just want to make this type of mobile application using flutter..._ 
[](https://www.quora.com/Can-I-go-offline-from-WhatsApp-without-disconnecting-from-the-Internet)
