### ISSUE TITLE
SetState Conflict

### ISSUE THREAD

**Issue by adlucio87** [miguelpruivo/plugins_flutter_file_picker#129]
Hi,

i'm using this plugin in my app and it is amazing. thanks for your work.

I'have an issue, i am not sure if i cause this issue with my code or is this plugin that cause it.
My issue is relative on setstate command for rebuilding ui.

After reciving file path:
filepath = await FilePicker.getFilePath
i need to process file and i like to make a loading animation.
so i use setstate but it does'nt work.
If i start my animation befor call  FilePicker.getFilePath after that my animation disappered.
How can i do that?

Thanks
Andrea

**Comment by miguelpruivo** [comment]
Hi! 

This _probably_ has nothing to do with the plugin itself, but it’s ok to help you anyway.

Your file picking step is ok, then, I assume that you’ll do some kind of processing, in which you should be using some kind of animation. That should be possible, but just make sure that you aren’t calling setState when your widget tree is rebuilding.

**Comment by adlucio87** [comment]
Hi,
thanks for your quickly reply, it was my issue. I solve it :)
Sorry but i am nubie in flutter, i call asyn process method without waiting so setstate update and reupdate interface too quik.
thanks
Andrea
