### ISSUE TITLE
Documents only FileType

### ISSUE THREAD

**Issue by I-am-original** [miguelpruivo/plugins_flutter_file_picker#16]
It should not be hard to create FileType and filter files only by documents extensions. like pdf, doc(x), xml, txt, etc.

Is it possible to do?

**Comment by Stnieder** [comment]
That would be awesome.

**Comment by miguelpruivo** [comment]
Yes. That should be fine. I’ll work on it for a future update that should come later this month.

**Comment by MarcelLamotheNH** [comment]
Along the same lines, it'd be useful if it could be restricted to selecting only directories.

**Comment by miguelpruivo** [comment]
Closing issue. Version 1.1.0 released with custom file extensions filter as suggested. [See changelog](https://pub.dartlang.org/packages/file_picker#-changelog-tab-)

**Comment by I-am-original** [comment]
@miguelpruivo thanks ) great
