### ISSUE TITLE
No file selected

### ISSUE THREAD

**Issue by rohaanhamid** [miguelpruivo/plugins_flutter_file_picker#18]
I tried it on an Android Emulator running Android Oreo and I don't get a valid path to the selected file. Instead I get the location of the cache folder {path_to_app}/cache/Documents/.

**Comment by miguelpruivo** [comment]
You're probably loading a file from a cloud (like GDrive). If so, that has already been fixed for a while on the `beta` branch. If not, just let me know so I can take a look. I'm looking to PR an updated version by this week.
