### ISSUE TITLE
Cancel picking a file and then pick again throws an error and breaks the app

### ISSUE THREAD

**Issue by pushangupta** [miguelpruivo/plugins_flutter_file_picker#20]
Try to cancel the first request of picking the file and then reopen the file picker. It throws a Platform Exception which, is not being caught in PlatformException

```

    Future getBrochure() async {
    try {
      await FilePicker.getFilePath(type: FileType.ANY)
          .catchError((error) => print(error))
          .then((brochure_path) {
            print("Completed");
        if (brochure_path != "" || brochure_path != null) {
          print("fired");
          setState(() {
            brochure = File(brochure_path);
          });
        }
      });
    } on PlatformException catch (e) {
      print(e);
    }
  }
```

**Comment by miguelpruivo** [comment]
@pushangupta I've tried to re-create your issue even with your code and I can't seem to be able to replicate. Would you mind to add some logs?

**Comment by pushangupta** [comment]
@miguelpruivo 

![screen shot 2018-12-27 at 12 08 54 am](https://user-images.githubusercontent.com/7023840/50454173-c4d5b000-096b-11e9-9319-e34f4550968c.png)
![screen shot 2018-12-27 at 12 09 15 am](https://user-images.githubusercontent.com/7023840/50454176-c901cd80-096b-11e9-933d-495c81126e7e.png)


These are logs after running on IOS simulator

**Comment by pushangupta** [comment]
@miguelpruivo I think your ios delegate file misses to hit the "canceled by the user" case

**Comment by miguelpruivo** [comment]
Thank you @pushangupta I've found the issue and it is already solved in the `beta`. I'm looking to release a new version to dart pub soon with this fixed and also new features such as custom file type filtering (between today and tomorrow).

**Comment by pushangupta** [comment]
@miguelpruivo Glad to hear that. I am really looking forward for your release. Keep it up!

**Comment by miguelpruivo** [comment]
Released. [See changelog](https://pub.dartlang.org/packages/file_picker#-changelog-tab-)
