### ISSUE TITLE
Can I remove CAMERA permission?

### ISSUE THREAD

**Issue by kgamecarter** [miguelpruivo/plugins_flutter_file_picker#21]
If I don't need FileType.CAMERA.
Can I remove CAMERA permission?

If my app has CAMERA permission. I need give google play privacy policy url.

**Comment by kgamecarter** [comment]
I found camera permission is added by image_picker.
I think remove image_picker for FileType.IMAGE and FileType.CAMERA better.
Separate it for difference requirement.

**Comment by miguelpruivo** [comment]
If you don’t need it you don’t have to provide those permissions as well. The image_picker is just re-used here in order to prevent two packages but I get your idea. I’ll take in consideration.

**Comment by kgamecarter** [comment]
No. I don't give CAMERA permisiion in AndroidManifest.xml
But still appear CAMERA permission in app.
Untill I remove image_picker in my file_picker fork.

**Comment by kgamecarter** [comment]
https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/AndroidManifest.xml
image_picker will auto add permission.

**Comment by miguelpruivo** [comment]
That’s right, I forgot the `grantUriPermissions` is set to `true` on the image_picker.

**Comment by miguelpruivo** [comment]
I'll reopen so others may see this. I would like to have more feedback since I get the point, that it would be fine to have it separated in both plugins, but I can also understand that this is more reliable for some users since they have to only import one plugin and it will handle picking all file types.

**Comment by kgamecarter** [comment]
Just this
![1](https://i.imgur.com/UJtlkSV.png)
Google play asks me privacy policy
![2](https://i.imgur.com/PpsEXlM.png)

**Comment by miguelpruivo** [comment]
Hum, I see. The privacy policies. [This](https://community.thunkable.com/t/learn-how-to-create-privacy-policy-for-your-apps/1392?source_topic_id=3766) may be useful in the meantime.

**Comment by kgamecarter** [comment]
OK is a nice sample
[https://docs.google.com/document/d/14xHZa1PqxpgntwhStx0dnaiPOV1uDAY0RzQyF5GkPpw/edit](https://docs.google.com/document/d/14xHZa1PqxpgntwhStx0dnaiPOV1uDAY0RzQyF5GkPpw/edit)

But if some one just need pick document. remove useless permission better.

**Comment by 1abzar** [comment]
hi , I have this problem too, I want to remove the camera permission, plz help.

**Comment by miguelpruivo** [comment]
This is a tricky one because the plugin supports picking files from camera so it will always have to have that permission. 
One option will be removing this feature entirely and let users use this along with `image_picker` if needed.

**Comment by miguelpruivo** [comment]
Version 1.3.0 was deployed on dart pub and fixes this, alongside with other requested features and bug fixes. See [changelog](https://pub.dartlang.org/packages/file_picker#-changelog-tab-).

Thank you all for your feedback.
