### ISSUE TITLE
doesn't work on older android versions supported by flutter 16+

### ISSUE THREAD

**Issue by afamobius** [miguelpruivo/plugins_flutter_file_picker#25]

**Comment by miguelpruivo** [comment]
Can you be clear about which version you’re referring to?

**Comment by miguelpruivo** [comment]
Can you fork it and give it a try? I’m not able at the moment. If it works make a PR. 

Thank you.

**Comment by afamobius** [comment]
okay I will try

**Comment by afamobius** [comment]
didn't help , android 16 17 18 are not working with this plugin

**Comment by afamobius** [comment]
I found a solution , it is a problem with android itself , below android 5 lollipop , phones have Downloads app not File Manger app , so to use apps that use this plugin , the phone needs to have a file manager like ES File Manager , I'm gonna close this issue since I found a solution

**Comment by miguelpruivo** [comment]
Yes, thank you for pointing that. I forgot to mention that the phone always need a FileExplorer to handle the intent that is made, after api 19 there is a native explorer provided with Android which should always be the preferred one for this plugin.

There are however, one issue reported from an user that has a custom FileProvider from a custom rom (I believe a lenovo rom from a Moto phone) which somehow won't provide the correct path neither will open the native explorer.
