### ISSUE TITLE
New feature: Multiple file picker

### ISSUE THREAD

**Issue by ChiefWiggum** [miguelpruivo/plugins_flutter_file_picker#27]
It would be great to have a method `getFilePaths` which allows the selection of multiple files, if the native picker allow this behaviour (not sure).
This method would then not return a single path, but a list/array of paths.

Does anyone know if the native file explorers support this behaviour?

**Comment by ChiefWiggum** [comment]
Looking at the [UIDocumentPickerViewController](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller) it seems to support selecting multiple files when setting `allowsMultipleSelection` to `true` on **iOS**.

On **Android** it might be possible by using [EXTRA_ALLOW_MULTIPLE](https://developer.android.com/reference/android/content/Intent#EXTRA_ALLOW_MULTIPLE).

But we would have to use another ImagePicker, since the current one, afaik, does not support the selection of multiple files. Maybe [multi_image_picker ](https://pub.dartlang.org/packages/multi_image_picker) would work?

**Comment by miguelpruivo** [comment]
Yes, there is a way on both platform that supports multiple file picking, however that wasn't the first purpose of this plugin. However is a nice to have that may be added in a future update.

**Comment by miguelpruivo** [comment]
**Version 1.3.0** was deployed on dart pub and adds this, alongside with other requested features and bug fixes. See full [changelog](https://pub.dartlang.org/packages/file_picker#-changelog-tab-).

Make sure you clean and change your pubspec to the latest version: `file_picker: ^1.3.0`

Thank you all for your feedback.

**Comment by miguelpruivo** [comment]
@ChiefWiggum as of now, with version [1.6.0 released just now](https://pub.dev/packages/file_picker#160) you can start filtering multiple extensions at once. There are breaking changes, so have in mind that from now on you'll need to provide an `List` of file types instead of a single one with `FileType.custom`.

Example:
```
 List<File> files = await FilePicker.getMultiFile(
          type: FileType.custom,
          allowedExtensions: ['jpg', 'pdf', 'doc'],
        );
```
Thank you.

**Comment by ChiefWiggum** [comment]
Awesome, thank you. We'll give it a try in a few days.
