### ISSUE TITLE
Error while building on android device : Saying -this dependencies aren't compatible with AndroidX.

### ISSUE THREAD

**Issue by ditheshthegreat** [miguelpruivo/plugins_flutter_file_picker#37]
Recently I updated flutter package and after that i cant build my app.

`D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler
         *********************************************************
WARNING: This version of image_picker will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\51.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\41.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\23.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\35.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\73.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\45.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\39.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\67.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\59.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\79.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\55.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\63.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\27.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\25.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\33.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\53.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\19.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\21.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\71.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\47.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\37.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\81.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\75.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\43.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\77.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\69.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\49.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\65.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\29.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\61.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\57.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\31.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\12.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\1.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\5.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\11.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\4.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\3.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\8.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\14.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\10.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\7.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\9.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\2.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\13.jar, E:\Flutter Projects\coupled\build\app\intermediates\transforms\dexBuilder\debug\6.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.media.MediaBrowserCompat$CallbackHandler

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
Finished with error: Gradle task assembleDebug failed with exit code 1
`

Flutter Doctor

`[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.107], locale en-US)
    • Flutter version 1.0.0 at E:\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)`

**Comment by miguelpruivo** [comment]
This doesn’t look like an actually issue with this plugin. 

By your stack trace either you have an incompatibility in your app with android X or look like somehow one of the plugins you’re using has a duplicated flutter.jar library in its `build.gradle` which usually results in that exception.
