### ISSUE TITLE
Issue with gauriinfotech

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [miguelpruivo/plugins_flutter_file_picker#4]
This Android dependency: https://github.com/miguelpruivo/plugins_flutter_file_picker/blob/1f83dfa776e667552cbc435690ca2cac7e5e9159/android/build.gradle#L37
It is causing an issue, which prevents the application to build, i.e. the following:

```
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed
```

```
Attribute application@label value=(ANDROID_APP_NAME) from AndroidManifest.xml:17:9-28
	is also present at [in.gauriinfotech:commons:1.0.8] AndroidManifest.xml:13:9-41 value=(@string/app_name).
	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:15:5-38:19 to override.
```

I am not sure for what this dependency is required, but this is definitely an issue. I also do not know if this is even fixable in the plugin without removing the dependency.

**Comment by miguelpruivo** [comment]
Fixed on the last version. Dependency removed. It was only necessary to retrieve the path.
