### ISSUE TITLE
Multiple File Types

### ISSUE THREAD

**Issue by SJente** [miguelpruivo/plugins_flutter_file_picker#42]
Hello Miquel,

I'm working on an application where i want to allow different kind of file types as described in <a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="400808216" data-permission-text="Issue title is private" data-hovercard-type="issue" data-hovercard-url="/miguelpruivo/plugins_flutter_file_picker/issues/27/hovercard" href="https://github.com/miguelpruivo/plugins_flutter_file_picker/issues/27" aria-label="#27, New feature: Multiple file picker">#27</a>.

I have read that you maybe were going to implement this feature in the future. I was wondering if this possible feature was still on your to-do list because i could really use it. 

Thanks for your great work on this, really love how compact and smooth it works. 

Thanks in advance,
SJente

**Comment by miguelpruivo** [comment]
Hi. Thank you for your suggestion, this was already been requested in #27 as you've correctly mentioned and it's being worked on - actually it's already done on iOS and, at the time of this answer, it's being implemented on Android as well. 

This will be deployed along with some other requested improvements in the `1.3.0` probably by the end of the week.

Thank you for your patience.

**Comment by SJente** [comment]
Great to hear @miguelpruivo, i'm looking forward to using this plugin in my application!

**Comment by miguelpruivo** [comment]
**Version 1.3.0** was deployed on dart pub and adds this, alongside with other requested features and bug fixes. See [changelog](https://pub.dartlang.org/packages/file_picker#-changelog-tab-).

Make sure you clean and change your pubspec to the latest version: `file_picker: ^1.3.0`

Thank you for your feedback.

**Comment by miguelpruivo** [comment]
@SJente as of now, with version [1.6.0 released just now](https://pub.dev/packages/file_picker#160) you can start filtering multiple extensions at once. There are breaking changes, so have in mind that from now on you'll need to provide an `List` of file types instead of a single one with `FileType.custom`.

Example:
```
 List<File> files = await FilePicker.getMultiFile(
          type: FileType.custom,
          allowedExtensions: ['jpg', 'pdf', 'doc'],
        );
```
Thank you.
