### ISSUE TITLE
Lack of cancel handling in Android, possibly memory leaks

### ISSUE THREAD

**Issue by nagoya0** [miguelpruivo/plugins_flutter_file_picker#43]
Hello Miguel,

I'm working on an application using this excellent plugin, and I noticed that FilePicker does not callback if I close file picker in Android.

Because of this, await FilePicker.getFilePath() function call never returns, and occurs memory leaks.

https://github.com/miguelpruivo/plugins_flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FilePickerPlugin.java#L50

if user closes file manager, OS calls onActivityResult() and sets resultCode to Activity.RESULT_CANCEL.

**Comment by miguelpruivo** [comment]
Hi. Looks like a dup of #28. This is already being done. Looking forward a new version with this and more later this week. 

Thank you.

**Comment by nagoya0** [comment]
Thank you for your quick response.

I checked issue #28 and branch #Roadmap-1.3.0, but it looks like another issue.

Main cause of this issue is, program doesn't call result.success(null) when (resultCode == Activity.RESULT_CANCELED).

**Comment by miguelpruivo** [comment]
Ok. That's actually when you dismiss the picker and the event is not handled. This is already being handled on iOS but not on Android. I'll add it to the coming update too since it doesn't add much overhead. 

Re-opening.
Thank you for the feedback.

**Comment by miguelpruivo** [comment]
**Version 1.3.0** was deployed on dart pub and fixes this, alongside with other requested features and bug fixes. See [changelog](https://pub.dartlang.org/packages/file_picker#-changelog-tab-).

Make sure you clean and change your pubspec to the latest version: `file_picker: ^1.3.0`

Thank you for your feedback.
