### ISSUE TITLE
Removing the need of WRITE permission

### ISSUE THREAD

**Issue by pjkroll** [miguelpruivo/plugins_flutter_file_picker#54]
Dart:
```
String getPath(..., {String destinationPath});
```

Android:
```
sourceUri = choosenFile();
resolver = getContentResolver();
writeToFile(resolver, sourceUri, destinationPath);
```

IOS:
`???`

**Comment by miguelpruivo** [comment]
You can’t remove the permission to write files because if somebody wants to actually modify a remote file (such as files in google drive) you need them to first be cached. You can’t open a file descriptor for a URI of a remote file.

**Comment by pjkroll** [comment]
This is the whole idea of openable content.
```
intent = new Intent(Intent.ACTION_GET_CONTENT);
intent.addCategory(Intent.CATEGORY_OPENABLE);
```
You don't have to have access to all the files if you want only the content of the file picked by the user. The user gives you explicit permission to this one file. 
Extracting the path from content:/  uri is just the trick. And it is the wrong way to do it. It won't always work.

By starting the intent you are only guaranteed that you will have access to the file by calling:
```
getContentResolver().openInputStream(uri)
```
And this access is only temporarily. You should create your own copy.

How Google Drive work:
-  user picks the file from Drive
-  Drive downloads the file to its private directory (this file is temporary),
-  Drive creates the URI to the file, the file is temporarly available through FileProvider of the Google Drive
- here you can/should make your own copy. You can do it to your private external storage. Since KitKat you don't need any permission to do it.

Android:
```
sourceUri = choosenFile();
inputStream = getContentResolver().openInputStream(sourceUri);
fileName = extractFileName(sourceUri);
writeToFile(inputStream, destinationDirectory, fileName);
```
 Dart:
```
/// destinationDirectory is a path to the directory where the app has write permission  
String getPath(..., {String destinationDirectory});
```

**Comment by miguelpruivo** [comment]
I’m aware of that approach. However for
API > 15 & < KitKat you still need to ask for permissions. 

The problem with that, is if the user wants to extract the absolute path of the file, let’s say, to save some other files in that directory, I’m not sure if that will be possible using the content resolver.

**Comment by pjkroll** [comment]
> API > 15 & < KitKat you still need to ask for permissions.
```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
                     android:maxSdkVersion="18" />
```

> How what would happen, for an instance, in your provided example, if the user don’t give a destinationPath? Would you just use the default temp directory directly?

Or if the user doesn't provide destinationPath, you can just call getPath() in the old way.
But the getPath() is always a path to a file that should be treated as temporary. The FileProvider can remove it at any time. 

You should be aware that URI could be something like this: content://com.google.drive/files/document.pdf
You won't ever have access to this file.

**Comment by miguelpruivo** [comment]
>You should be aware that URI could be >something like this: >content://com.google.drive/files/document.pdf
>You won't ever have access to this file. You >can only get it through >getContentResolver()

This is something that is already being made somehow. Check the android `FileUtils.java` source.

**Comment by pjkroll** [comment]
That is great! It is everything you need to create this feature. But the decision is up to you, if you want it. I don't have right now the possibility to test it and make a pull request.

**Comment by miguelpruivo** [comment]
This has been already done in `1.3.6`. Thank you.
