### ISSUE TITLE
Platform exception: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by TheHemantKaushik** [miguelpruivo/plugins_flutter_file_picker#56]
Hi,

**I am getting following error when I try to select any file:**

I/FilePicker(13338): Checking permission: android.permission.WRITE_EXTERNAL_STORAGE
I/FilePicker(13338): Requesting permission: android.permission.WRITE_EXTERNAL_STORAGE
E/MethodChannel#file_picker(13338): Failed to handle method call
E/MethodChannel#file_picker(13338): java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
E/MethodChannel#file_picker(13338): 	at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:696)
E/MethodChannel#file_picker(13338): 	at androidx.fragment.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:711)
E/MethodChannel#file_picker(13338): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:500)
E/MethodChannel#file_picker(13338): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin.requestPermission(FilePickerPlugin.java:130)
E/MethodChannel#file_picker(13338): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin.startFileExplorer(FilePickerPlugin.java:180)
E/MethodChannel#file_picker(13338): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin.onMethodCall(FilePickerPlugin.java:115)
E/MethodChannel#file_picker(13338): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#file_picker(13338): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#file_picker(13338): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#file_picker(13338): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#file_picker(13338): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#file_picker(13338): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#file_picker(13338): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#file_picker(13338): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#file_picker(13338): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#file_picker(13338): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (13338): [FilePicker] Platform exception: PlatformException(error, Can only use lower 16 bits for requestCode, null)
W/ManagedChannelImpl(13338): [{0}] Failed to resolve name. status={1}

**Here is the report from `flutter doctor -v`:**

[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
    • Flutter version 1.2.1 at /Applications/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Applications/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Applications/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.5.app/Contents
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by miguelpruivo** [comment]
What is the `file_picker` version that you are using?

**Comment by TheHemantKaushik** [comment]
1.3.2

**Comment by miguelpruivo** [comment]
Does this happen always? Can you give it a try in the Android 8 (API 27) and let me know if it is working? Thank you.

**Comment by TheHemantKaushik** [comment]
I am trying all file types, with or without giving storage permissions. Same is happening on API 27, here is the details of my emulator:

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 8.1.0 (API 27) (emulator)

**Comment by miguelpruivo** [comment]
@TheHemantKaushik thank you for the insight. Is this happening if you use `FileType.IMAGE`?

**Comment by TheHemantKaushik** [comment]
Yes, it is happening with `FileType.IMAGE` as well as `FileType.AUDIO` and `FileType.VIDEO`.

**Comment by miguelpruivo** [comment]
Ok. I may take a look into it later today, if I have some time.

**Comment by miguelpruivo** [comment]
@TheHemantKaushik I'm looking into it to understand what is actually happening. Can you tell me what is your `targetSdk` of your main app? 

Thank you.

**Comment by miguelpruivo** [comment]
Also @TheHemantKaushik, can you post your app’s `build.gradle`? This looks like a very version related issue. Thank you.

**Comment by miguelpruivo** [comment]
This is fixed in `1.3.3`. However I would still like to have the info I've asked for so I could further investigate what was causing the issue.
