### ISSUE TITLE
[FilePicker] Unsupported operation. MissingPluginException

### ISSUE THREAD

**Issue by prasant10050** [miguelpruivo/plugins_flutter_file_picker#61]
[FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method __CUSTOM_pdf on channel file_picker)

**Comment by miguelpruivo** [comment]
Hi. This is too vague. Can you provide the steps? It looks like you are trying to pick a pdf which should be ok.

**Comment by prasant10050** [comment]
done

**Comment by miguelpruivo** [comment]
Did it fixed for you?

**Comment by prasant10050** [comment]
Yeah. I fixed
