### ISSUE TITLE
How to get URL file

### ISSUE THREAD

**Issue by anhtu0101** [miguelpruivo/plugins_flutter_file_picker#63]
After I select a file from Google Drive, DropBox, is there a way for me to get url for image?
Ex: Url Image: https://drive.google.com/file/d/10qJfAEHCPaVC9o-Xbz6K__0NRCWwMa9d/view
Many Thank

**Comment by miguelpruivo** [comment]
Hi @anhtu0101 , I'm afraid that currently not. When you select a remote file what happens is that this file will be cached locally so you can actually access its absolute path and work with it (eg. modify, upload it, etc.). 

What you are looking for is a remote URI for that file. It's a bit out of what this package does and may lead to users expecting an absolute path and instead loading a remote, but it's a good suggestion. May consider it in a separate method in a future (eg. `getRemotePath()` which will only allow to select paths from clouds).

**Comment by anhtu0101** [comment]
@miguelpruivo Thank you for your support, this is a great Packages...

**Comment by miguelpruivo** [comment]
Moved to #99.
