### ISSUE TITLE
Add support for limiting file selection

### ISSUE THREAD

**Issue by sarbagyastha** [miguelpruivo/plugins_flutter_file_picker#64]
It will be great if limit for maximum number for files could be enforced in multi file picker option.

**Comment by miguelpruivo** [comment]
Hi @sarbagyastha, currently, and to provide a seamless experience across platforms, I don't believe that's possible with native pickers. Either you limit to one item or any. But you can always protect this within your app side by discarding N+ elements, displaying a message to the user, etc. 

An alternative would be to use a custom picker, but that's not the purpose of this package.

Nevertheless, thank you for your suggestion.
