### ISSUE TITLE
Cannot build for Android (version 1.3.4)

### ISSUE THREAD

**Issue by hchris0** [miguelpruivo/plugins_flutter_file_picker#72]
Trying to build with version 1.3.4 and getting the following error:

`FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':file_picker:debugCompileClasspath'.
> Failed to transform file 'flutter.jar' to match attributes {artifactType=processed-jar} using transform JetifyTransform
   > Failed to transform '/Users/miguelruivo/DevTools/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar' using Jetifier. Reason: Cannot open a library at 'FileMapping(from=/Users/miguelruivo/DevTools/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar, to=/home/chris/.gradle/caches/transforms-1/files-1.1/flutter.jar/238118fc2d1bd61f2da6041b9800dfc1/jetified-flutter.jar)'. (Run with --stacktrace for more details.)
`

Project builds fine with version 1.3.3.

**Comment by miguelpruivo** [comment]
Thank you for noticing and reporting this so fast. I published for the pub.dartlang a version that had a local dependency in the `build.gradle` when it shouldn't and this would cause every Android build that uses `1.3.4` to fail. 

A fix is [already deployed](https://pub.dartlang.org/packages/file_picker#-changelog-tab-) with version `1.3.4+1`. 

Just let me know if it's all working as it should again and, once more, thank you for reporting.

**Comment by hchris0** [comment]
Thank you for the fast fix :)

It is now working again as intended.
