### ISSUE TITLE
Can't pick photo from google photos, can it possible?

### ISSUE THREAD

**Issue by vitulgoyani** [miguelpruivo/plugins_flutter_file_picker#74]
I was tried to pick a photo from Google photos but it generates an error

**Comment by miguelpruivo** [comment]
@vitulgoyani hi. Would you mind post your logs? Also which version from the picker are you using? 

Just make sure beforehand that you’ve internet connection and the internet permission in your iOS/Android plist/manifest file respectively.

**Comment by vitulgoyani** [comment]
I/flutter (14598): [FilePicker] Unsupported operation. Method not found. The exception thrown was: NoSuchMethodError: The method 'split' was called on null.
I/flutter (14598): Receiver: null
I/flutter (14598): Tried calling: split("/")

And I used the latest version from git

**Comment by vitulgoyani** [comment]
it was working fine with google drive but not work with google photos

**Comment by miguelpruivo** [comment]
@vitulgoyani  looks like a dup of #58 that should have already been fixed. What are the steps to replicate the issue?

**Comment by miguelpruivo** [comment]
@vitulgoyani is this still a problem for you?

**Comment by miguelpruivo** [comment]
Closing due to no further info. Feel free to reopen it if you still experience the same issue.
