### ISSUE TITLE
File Picker window not open 

### ISSUE THREAD

**Issue by VyasPrachi** [miguelpruivo/plugins_flutter_file_picker#75]
Hello @miguelpruivo,

I have applied the same code from example but I am getting given below error:

**I/flutter ( 7186): [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method ANY on channel file_picker)**

Please help me out.

**Comment by miguelpruivo** [comment]
@VyasPrachi looks like you haven’t imported the package at all to your app (only the Dart part).

Can you show me how you’re importing it in your `pubspec.yaml`? 

Thank you.

**Comment by VyasPrachi** [comment]
Hi @miguelpruivo,

I have attached my pubspec.yaml code below:

`name: file_picker
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:  
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


file_picker: ^1.3.4+1
path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
`

**Comment by miguelpruivo** [comment]
> Hi @miguelpruivo,
> 
> Here, I have attached my pubspec.yaml code in .txt file :
> [pubspec.txt](https://github.com/miguelpruivo/plugins_flutter_file_picker/files/3130252/pubspec.txt)

Thank you @VyasPrachi. Looks like I’ve found your problem. You are importing it wrongly.

You should add this under the normal dependencies and not the dev ones like so:
```
dependencies:  
  flutter:
    sdk: flutter
  file_picker: 1.3.4+1
```

And remove this:
```
file_picker: ^1.3.4+1
path: ../
```

**Comment by VyasPrachi** [comment]
Hi @miguelpruivo,

If I am using like this it gives the error :

**Error on line 22, column 3 of pubspec.yaml: A package may not list itself as a dependency.

  file_picker: 1.3.4+1

  ^^^^^^^^^^^
pub get failed (65)
exit code 65**

[pubspec.txt](https://github.com/miguelpruivo/plugins_flutter_file_picker/files/3130307/pubspec.txt)

**Comment by miguelpruivo** [comment]
@VyasPrachi you can’t have the app itself with the same name. Change the first line where you have `name: file_picker` to the name of your app.

**Comment by VyasPrachi** [comment]
Hello @miguelpruivo,

Thank You So much it is working when I have changed my project name.

**Comment by nishit2397** [comment]
Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method custom on channel miguelruivo.flutter.plugins.filepicker)
 I am getting this error how to solve
 it?

**Comment by NiranjanShah** [comment]
on MacOS , same error

Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method image on channel miguelruivo.flutter.plugins.filepicker)

Kindly assist

**Comment by miguelpruivo** [comment]
Hi, which device is it running?

**Comment by NiranjanShah** [comment]
Mac Air

**Comment by miguelpruivo** [comment]
Yes, but which OS? iOS, Android?

**Comment by NiranjanShah** [comment]
it is for Mac Desktop app.

**Comment by miguelpruivo** [comment]
Currently the plugin doesn't support Flutter Desktop, only through Flutter GO.
