### ISSUE TITLE
Custom filter rule.

### ISSUE THREAD

**Issue by zouzhenglu** [miguelpruivo/plugins_flutter_file_picker#77]
May I custom a rule to filter the result? Such  as, I want to filter the maximum size of the file.

**Comment by miguelpruivo** [comment]
in theory, you could. But that wouldn’t prevent the files from showing up. I would only not allow files bigger than X to be loaded, but the user would always be able to select them before hand.

**Comment by miguelpruivo** [comment]
Moved to #99.
