### ISSUE TITLE
How do you select  file from dropbox

### ISSUE THREAD

**Issue by premtemp1** [miguelpruivo/plugins_flutter_file_picker#78]
Hello,
 How can I use this plugin to get file from dropbox or iCloud Drive

**Comment by miguelpruivo** [comment]
Hi @premtemp1 you may want to check the README file. There’s plenty examples there of how to setup and use this package. Anyway, a simple usage that allows you to pick files from clouds is:

```
String filePath = await FilePicker.getFilePath(type: FileType.ANY);
```

This will let you pick anything but feel free to use some extension filters if needed. 

Closing as this isn’t actually an issue.

**Comment by premtemp1** [comment]
@miguelpruivo ,
  I can pick the file from iCloud , However, gDrive nor dropbox 
does not show  as an option on iOS

**Comment by miguelpruivo** [comment]
@premtemp1 you’ve to have the Dropbox and/or google drive apps installed as well.
