### ISSUE TITLE
Cancelling the explorer app crashes..

### ISSUE THREAD

**Issue by aachan13** [miguelpruivo/plugins_flutter_file_picker#80]
File picker works well..

but when i Try to cancel the first request of picking the file. It throws a Platform Exception which, is not being caught in PlatformException. is there something wrong with my code? 
Im using the newest file picker already.

```
void getFilePath() async {
    try {
      String filePath = await FilePicker.getFilePath(type: FileType.ANY);
      if (filePath == '') {
         return;
      }
      
      setState(() {
        String basename = p.basename(filePath);
        this._filePath = basename;
      });
      
    } on PlatformException catch (e) {
      print("Error while picking the file: " + e.toString());
    }
  }
```

**Comment by miguelpruivo** [comment]
Hi @aachan13 , that's because it's already being catch in the package itself [see here](https://github.com/miguelpruivo/plugins_flutter_file_picker/blob/master/lib/file_picker.dart#L56). 

You should look for the `null` return which usually indicates a cancel event or any other exception.

**Comment by aachan13** [comment]
Thanks for your fast response!

im sorry i really not experienced on this.. what should i do? it keep crashing my app :(

![image](https://user-images.githubusercontent.com/26079577/57633765-98e36000-75d6-11e9-8e31-9245046c18b6.png)

**Comment by miguelpruivo** [comment]
@aachan13 this doesn't look directly related to the package. You should look to your `basename()` method and see where are you calling the `isNotEmpty` getter which seems to be `null`.

**Comment by aachan13** [comment]
ohhh i see! finally found it.. ._.

thank you mr miguel!
