### ISSUE TITLE
I/flutter (10973): [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method IMAGE on channel file_picker)

### ISSUE THREAD

**Issue by Loisgenesis** [miguelpruivo/plugins_flutter_file_picker#82]
I am using   file_picker: ^1.3.4+1 , I have also pasted the example code and ran it but it keeps printing   [FilePicker] Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method ANY on channel file_picker)
My project name is different, pls assist thanks

**Comment by miguelpruivo** [comment]
Looks like a dup of #75. Just make sure you have your project name right within your pubspec.

**Comment by Loisgenesis** [comment]
`flutter clean`  made it work, thanks a lot

**Comment by Arston24** [comment]
1. `flutter clean` 
2.  quit the flutter run process and start it up again

**Comment by jafar260698** [comment]
I am still getting this error Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)
E/flutter (19823): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method any on channel miguelruivo.flutter.plugins.filepicker)

**Comment by uzairleo** [comment]
am still getting this error Unsupported operation. Method not found.

**Comment by miguelpruivo** [comment]
Just for reference, looks related with #545.

**Comment by Shiva207892** [comment]
Unsupported operation. Method not found. The exception thrown was: MissingPluginException(No implementation found for method custom on channel miguelruivo.flutter.plugins.filepicker)

**Comment by janithcooray** [comment]
Same Issue when running on linux-debug
Tried:
flutter clean
flutter pub get 
and flutter run

i will try web and android to see if its just related to linux

**Comment by Chiyembekezo** [comment]
flutter clean
flutter pub get
and flutter run
Confirmed ! its working on mobile

**Comment by miguelpruivo** [comment]
This kind of issues typically are related with local builds that for some reason aren’t embedding the packages in build. Should be easily resolved with the steps mentioned above.

**Comment by EmmanuelAmet** [comment]
After running `flutter pub add file_picker` and writing the code implementation, do not hot reload the app, kill it, and then run it. Alternatively, you can follow the above steps mentioned:
`flutter clean`
`flutter pub get`
`flutter run`

**Comment by DIP-POLLEY** [comment]
The above method helps resolve many issues while installing a new package while running the app.

**Comment by mvharikrishnan** [comment]
Fix this issue by adding the following to H:\ecommerceapp\android\app\build.gradle:
android {
  compileSdkVersion 33
  ...
}

**Comment by safiullahpk611** [comment]
> After running `flutter pub add file_picker` and writing the code implementation, do not hot reload the app, kill it, and then run it. Alternatively, you can follow the above steps mentioned: `flutter clean` `flutter pub get` `flutter run`

the killing to app is woeking

**Comment by ujwalnk** [comment]
I don't hot restart does the job, terminating the app and restarting fixed the issue
