### ISSUE TITLE
App crashes on ios 10.3.3

### ISSUE THREAD

**Issue by IsaNascimento** [miguelpruivo/plugins_flutter_file_picker#86]
App crashes when trying to pick a document with `FileType.ANY`. I have already enabled icloud and cloudkit as shown in the image attached.

The error I get is this: 

`2019-05-28 10:57:44.467621-0300 Runner[337:25602] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[FilePickerPlugin documentPicker:didPickDocumentAtURL:]: unrecognized selector sent to instance 0x17d7f6a0'`

![Captura de Tela 2019-05-28 às 11 05 09](https://user-images.githubusercontent.com/16281356/58484511-946f8900-8138-11e9-9274-7f5f10af7df7.png)

**Comment by miguelpruivo** [comment]
Hi @IsaNascimento, which iOS version are you building on? Also, can you try enabling iCloud Documents?

Thank you.

**Comment by IsaNascimento** [comment]
Hi @miguelpruivo I am on IOS 10.3.3. I tried enabling iCloud Documents, got the same error.

**Comment by miguelpruivo** [comment]
Do you even see the File Picker opening or you get the immediate exception? I know that for iOS versions below 11 you need to have the CloudKit enabled.

**Comment by IsaNascimento** [comment]
I see it opening and I can navigate it but as soon as I click to "choose" a file, it closes, I get that exception and the app crashes or freezes.

**Comment by miguelpruivo** [comment]
I may have to take a look on this. Thank you for reporting.

**Comment by IsaNascimento** [comment]
@miguelpruivo just to let you know, I tried with a clean project (your example project) and the same thing happens.

**Comment by miguelpruivo** [comment]
@IsaNascimento that may be possible. I confess that I've not digging much about running it on versions below 11.0 because I don't even have `CloudKit` enabled.

**Comment by miguelpruivo** [comment]
I'm looking into it @IsaNascimento. I'll keep you updated.

**Comment by IsaNascimento** [comment]
Alright, thank you @miguelpruivo.

**Comment by miguelpruivo** [comment]
@IsaNascimento I've found the issue and have already fixed it. I'm going to deploy a new version in a while.

**Comment by IsaNascimento** [comment]
That's great @miguelpruivo! Thank you so much! Also, what was the issue? I was starting to debug your code to try to help but obj-c isn't really my thing.

**Comment by miguelpruivo** [comment]
@IsaNascimento it was due to not having the correct delegate for the iCloud Drive in versions below iOS 11.

Can you please confirm that is working properly by replacing your `file_picker` dependency in the `pubspec` pointing to  `beta`? 
```
  file_picker:
    git:
      url: https://github.com/miguelpruivo/plugins_flutter_file_picker.git
      ref: beta
```

If everything is fine, just let me know, so I can deploy it to the dart pub.

Thank you!

**Comment by IsaNascimento** [comment]
@miguelpruivo just tested it and it's working.

**Comment by miguelpruivo** [comment]
@IsaNascimento all done. The [1.3.5](https://pub.dev/packages/file_picker#-changelog-tab-) is out. 

You can now use it normally as before (`file_picker: ^1.3.5`).

Thank you for your feedback.

**Comment by mehdisam** [comment]
documentPicker:didPickDocumentAtURL: is deprecated in iOS 11.0 and it is replaced by documentPicker:didPickDocumentsAtURLs: yeah single 's' added to it, but you have to implement both for backward compatibility.
