### ISSUE TITLE
Multi image picker

### ISSUE THREAD

**Issue by nguyenxuankiet262** [miguelpruivo/plugins_flutter_file_picker#88]
I turned on multi pick but it not work.

**Comment by miguelpruivo** [comment]
@nguyenxuankiet262 I need more details. Platform? Version? Which type are you trying?

Remember that in some Android versions you must hold for a while the file, in order to make the multi selection appear.

**Comment by nguyenxuankiet262** [comment]
Oh god! Tks for early replying. I forgot this " some Android versions you must hold for a while the file". Sorry my bad
