### ISSUE TITLE
Only allow to pick file from iCloud, not Dropbox or google drive

### ISSUE THREAD

**Issue by premtemp1** [miguelpruivo/plugins_flutter_file_picker#91]
Hello,
 On iOS , I only see the iCloud option. How do get from Google drive and Dropbox to available options

Thanks

**Comment by miguelpruivo** [comment]
Replied in #78.

**Comment by premtemp1** [comment]
Thanks .. Do you have an example of how to read the content of the file

**Comment by miguelpruivo** [comment]
@premtemp1 what do you mean?

**Comment by premtemp1** [comment]
Sorry man... but I know this maybe outside the scope..

I get the file name from your plugin
/Users//Library/Developer/CoreSimulator/Devices/A509517C-AC3F-4F87-856A-145F61075E8B/data/Containers/Data/Application/FC2B634B-F7BD-48EB-9B80-920476E20DE8/tmp/com.xyx-Inbox/myfile.doc'

Now I want to read the content and this is my code

File file =  new File(path);

  Stream<List> inputStream = file.openRead();

  inputStream
      .transform(utf8.decoder)       // Decode bytes to UTF-8.
      .transform(new LineSplitter()) // Convert stream to individual lines.
      .listen((String line) {        // Process results.
      },
      onDone: () { print('File is now closed.'); },
      onError: (e) { print(e.toString()); });


However, I get the error

flutter: FileSystemException: Failed to decode data using encoding 'utf-8'


Not sure how to get the content

**Comment by miguelpruivo** [comment]
You want to extract the text from the doc file?

**Comment by brijeshbodariya** [comment]
On iOS , How to see the iCloud option in flutter ??
