### ISSUE TITLE
Lost connection to device

### ISSUE THREAD

**Issue by kamrancr7** [miguelpruivo/plugins_flutter_file_picker#92]
It's open the recent files by default but when i go to the Files option and then Download and then i pick any file then my application is closed and Lost connection to device message is showing in console

D/libEGL  (21035): ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x0)
D/Surface (21035): Surface::disconnect(this=0x73666d1000,api=1)
D/Surface (21035): Surface::disconnect(this=0x73666d1000,api=-1)
D/libEGL  (21035): ARC_TRACE: ARCASM_eglMakeCurrent(ctx:0x7367bf4cb8)
D/Surface (21035): Surface::disconnect(this=0x73666d0000,api=1)
V/PhoneWindow(21035): DecorView setVisiblity: visibility = 4, Parent = ViewRoot{1019cdb com.example.iamflexiapp/com.example.iamflexiapp.MainActivity,ident = 0}, this = DecorView@73f05d5[MainActivity]
Lost connection to device.

**Comment by miguelpruivo** [comment]
Hi, @kamrancr7, I’m sorry, but I can’t seem to find anything related to the package itself in the stacktrace. 

May I ask you to run in another device/emulator and see if it’s still happening? 

Thank you.

**Comment by miguelpruivo** [comment]
@kamrancr7 do you still have this issue?

**Comment by miguelpruivo** [comment]
Since no further information was provided, I'll assume that you've resolved your issue. Feel free to reopen it otherwise.

**Comment by braysonjohn148** [comment]
I am getting this error too. I was using image_picker 0.7.4. i decided to try file picker. But i get the same issue. 
`D/FilePickerDelegate(18723): Selected type image/*
V/PhoneWindow(18723): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@951e92, this = DecorView@5bab063[MainActivity]
D/Surface (18723): Surface::disconnect(this=0x97371000,api=1)
D/Surface (18723): Surface::disconnect(this=0x97371000,api=-1)
D/Surface (18723): Surface::disconnect(this=0x976ec800,api=1)
D/SharedPreferencesImpl(18723): Time required to fsync /data/user/0/com.xcgx.droopy/shared_prefs/com.google.android.gms.measurement.prefs.xml: [<1: 0, <2: 1, <4: 2, <8: 1, <16: 1, <32: 2, <64: 1, <128: 0, <256: 1, <512: 0, <1024: 2, <2048: 0, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
V/PhoneWindow(18723): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@951e92, this = DecorView@5bab063[MainActivity]
2
I/AudioTrack(18723): force set policy to foreground flag:1 Priority:-16
Lost connection to device.
`
