### ISSUE TITLE
pls add feature where in code i will gave the path and type and get list of files.

### ISSUE THREAD

**Issue by kw2019ltd** [miguelpruivo/plugins_flutter_file_picker#98]

**Comment by miguelpruivo** [comment]
Hi, thank you for the suggestion, but I don’t quite get what you’re asking for.

May you provide an example?

**Comment by miguelpruivo** [comment]
Since there's not enough info on this, I'm closing it. Feel free to reopen if you have more details of what you're suggesting.

Thank you.
